language: node_js
cache: yarn
deploy:
  - provider: npm
    on: develop
    tag: next
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
  - provider: npm
    on: master
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY